### ISSUE TITLE
Accented characters are not printed in the pdf output

### ISSUE THREAD

**Issue by thakursagar** [cajuncoding/ApacheFOP.Serverless#1] opened 2021-03-02 17:50 UTC
Hi,

I am using your repo to generate pdfs generated by using XSL FO transformation. I found an instance where if the data contained special accented characters such as `Ajdarević`, the final output displays `Ajdarevi#`. I tried changing the font family in the XSL FO but it still doesn't display all accented characters. What would be the best way to handle this? Is there any way to set UTF-8 encoding on the ByteArrayOutputStream?

Thanks!

**Comment by cajuncoding** [comment] 2021-03-02 17:58
Hmmm, that's a good question.  Can you provide more details?

1. Are you using XSLT to render the XSL-FO markup? Or another templating language?
2. When you look at the raw XSL-FO markup do the characters render correctly?
3. Are you using the Fonet (.Net) rendering engine? Or are you using ApacheFOP.Serverless?

**Comment by thakursagar** [comment] 2021-03-02 18:40
1. yes using XSLT to render XSL-FO markup.
2. yes when i look at the raw XSL-FO markup i can see the characters correctly.
3. using the ApacheFOP.Serverless azure function app

**Comment by cajuncoding** [comment] 2021-03-02 21:07
Ok next step is can you try rendering the Apach FOP sample fonts.fo directly downloaded from their site and see if the characters render correctly?

https://xmlgraphics.apache.org/fop/fo/fonts.fo

**Comment by thakursagar** [comment] 2021-03-02 22:25
Sorry but how do i render it directly? I tried using the solution mentioned here but that didn't work for me - [link](https://stackoverflow.com/questions/51258443/polish-special-letters-not-available-while-using-apache-fop).

**Comment by cajuncoding** [comment] 2021-03-03 05:45
There's an example screenshot of using Postman to sent the FO markup directly to the service for rendering:
https://github.com/cajuncoding/ApacheFOP.Serverless#postman-example

Based on your answers above, I assume you have an instance of ApacheFOP.Serverless deployed to Azure Functions (or similar).  It's just a REST API endpoint that receives the well-formed FO markup from the payload sent as POST request.  If it's parsed and rendered successfully you will get a binary response back.  In Postman this will look like binary goblede-goop, but you can just click to "Save Response" and save as a binary PDF file which you can then view in a PDF Viewer...

![image](https://user-images.githubusercontent.com/20844814/109758537-57f47b00-7bb1-11eb-86ef-b2e3ffe8085a.png)

**Comment by cajuncoding** [comment] 2021-03-03 05:46
I expect that you should see a valid result as I do using my test deployment as follows:
![image](https://user-images.githubusercontent.com/20844814/109758673-8e31fa80-7bb1-11eb-827e-e2cf45e31c59.png)

**Comment by thakursagar** [comment] 2021-03-03 16:02
Thanks for the detailed explanation. I am not getting the same output as you. I get an error which complains about the `&` character being present in the body. Here is a screenshot:
![image](https://user-images.githubusercontent.com/11203361/109834112-dbdd5000-7c0f-11eb-9d35-7716e987579a.png)

**Comment by thakursagar** [comment] 2021-03-03 16:08
I'll try escaping those characters in the body and see if that fixes it

**Comment by thakursagar** [comment] 2021-03-03 16:12
yep escaping the characters worked and i get the same output as you. what does this mean in the context of the issue though? i still think the fonts and character included in this file do not support all the special characters that I am looking for - like in the example `Ajdarević`?

**Comment by thakursagar** [comment] 2021-03-03 16:55
I found a solution. i created a config which points to windows fonts on my pc, changed the font-family on xsl-fo so that it uses the font which has support for these characters and that worked.

**Comment by cajuncoding** [comment] 2021-03-03 17:02
Great! Glad you found the solution.... I knew that it was likely a font related issue if the Fonts.fo rendered correctly.  👍

Coincidentally, I'm enhancing the project to more easily load configuration so that I can add in specific fonts not normally included when deployed.... Arial.ttf, etc.  As Apache FOP notes in their docs they only include a small set of Fonts (which has often been enough), but anything more requires providing the Font files and updating the configuration as you have done :-)

**Comment by cajuncoding** [comment] 2021-03-04 07:04
@thakursagar FYI, I was actually working on this right when you logged this ticket, so I wanted to let you know I've now wrapped up the enhancements.

I've now incorporated this exact configuration feature into the main branch of `ApacheFOP.Serverless`.  As you noted previously the project was relying on all the default config values, but now it dynamically loads them from the xml configuration file in `/src/main/resources/apache-fop-config.xml` that is bundled and deployed with the project (via maven).  The included config now enables Font 'auto-detect' by default now :-)

This enables the fonts and is working well for me in a Windows Azure Function deployment :-).... and was needed for my current project work.  So maybe this helps others also!

**Comment by cajuncoding** [comment] 2021-03-04 07:21
Closing this issue; root cause was not an issue with the project but in the Configuration of Apache FOP fonts needed.

However, I want to note that new enhancements with v1.1 very recently added do make the project more resilient against Font related issues by enabling xml configuration customization that now turns on the Font `auto-detect` feature by default.

**Closed by cajuncoding** 2021-03-04 07:21 UTC
