### ISSUE TITLE
Server Can't Read Chunked HTTPClient Requests from .Net Core 

### ISSUE THREAD

**Issue by sfrerotte** [cajuncoding/ApacheFOP.Serverless#8] opened 2023-04-14 18:30 UTC
Hey @cajuncoding , I've think I've been hitting a weird incompatibility with a new .Net Core site I've been trying to set up. 

I believe it's related to this issue in .Net Core wherein you can't turn off chunked transfer encoding because the flag is a broken no-op:
https://github.com/aspnet/AspNetWebStack/issues/232

Been trying different combinations of your client call examples to make sure I didn't have anything wrong but after staring at Fiddler and playing with the responses it seems like Transfer-Encoding: chunked prevents the service from reading in the body and results in a 400 error each time. Editing the raw request to remove the chunked header and the padded bytes that adds results in a success.

Thought it might be worth a sanity check before I went back to WebClient to move forward. Thanks.

**Comment by cajuncoding** [comment] 2023-04-14 19:20
Hmmm we don’t have any issues with .NET…

Can you provide full details about your setup? What version of .NET specifically are you calling from? Are you using client from [Nuget](https://www.nuget.org/packages/PdfTemplating.XslFO.Render.ApacheFOP.Serverless)? I assume your using ApacheFOP serverless in an Azure Function right?

 We’re not having any issues with Asp NET Core for .NET 6.

Can you provide a small web app that reproduces the issue?

**Comment by cajuncoding** [comment] 2023-04-15 01:25
FYI just in case you weren’t using the client, here is the source (it uses[Flurl](https://flurl.dev/)  under the hood; can’t recommend it enough):
https://github.com/cajuncoding/PdfTemplating.XslFO/blob/0b13b8464bc41de30e420a3d201d8012b9845520/PdfTemplating.XslFO.Render.ApacheFOP.Serverless/ApacheFOPServerlessPdfRenderService.cs#L24

**Comment by cajuncoding** [comment] 2023-04-15 04:05
And regarding the server reading chunked requests…I can’t find any explicit docs yet but there is a bit of information out there implying that Azure Functions simply do not play well with chunked requests due to their highly transient nature (spinning up and spinning down as needed), and the fact that they do not support persistent Http connections by default (eg SignalR service is required for .Net functions).

So with that in mind, chunked requests are used when the request is extremely large or has unknown length.  In which case, a request of unknown length could result in being routed to different function invocations. Which is why many recommend a claim ticket type of pattern instead of a chunked request (eg. upload to Blob and then post the Blob details as the claim ticket). Or use single (atomic) requests and keep the total size under 100MB…

So it’s unlikely that chunked requests can even be supported at all. Therefore per  the title of this issue, this cannot fixed on the server side and isn’t really an issue of the server, per se.

As you alluded to, its more likely that the client is unnecessarily sending the request as chunked, because the XSL-FO payload size should be known;  the request is not of unknown size…

**Comment by sfrerotte** [comment] 2023-04-15 16:55
Thanks for the quick replies and digging into it. I’ll be able to send some small post request samples on Monday. We’re using Flurl elsewhere in our project so I may try that over using HTTPClient.

**Comment by sfrerotte** [comment] 2023-04-17 12:27
[Chunked_Request.txt](https://github.com/cajuncoding/ApacheFOP.Serverless/files/11250027/Chunked_Request.txt)
[Unchchunked_Request.txt](https://github.com/cajuncoding/ApacheFOP.Serverless/files/11250028/Unchchunked_Request.txt)

Here's an cleaned up example of the HttpClients Post to the service and a version of the same request that works without chunked. Since it won't let me override this Transfer-Encoding I'll try using the Flurl method you recommended.

**Comment by cajuncoding** [comment] 2023-04-19 01:34
@sfrerotte what I was hoping you would send is a reproduction of the issue in C#...  so I could see how you are attempting to make the request from C# because your issue is almost certainly in how you are making the request -- not in the server's processing of your Xsl-FO... which I can confirm rendered just fine via Postman:
![image](https://user-images.githubusercontent.com/20844814/232943556-8b905881-bd61-432e-bc5e-de5184c54125.png)

It is most likely has to do with that fact that the code you are using to send the request is not setting the `content-length` correctly and therefore it things the request is of unknown size so it's internally setting the request to be chunked...
![image](https://user-images.githubusercontent.com/20844814/232943527-024238f6-3597-478d-8758-d76fd4a27bdb.png)


I KNOW that this XslFO can render as I can

**Comment by cajuncoding** [comment] 2023-04-29 05:23
Closing this as all information points to the fact that Azur Functions inherently cannot support chunked requests of unknown sizes. 

And the issue — though not reproducible — is likely due to incorrectly calling the server from the client.

**Closed by cajuncoding** 2023-04-29 05:23 UTC
Labels: notanissue
